### ISSUE TITLE
Unsure of how the GAP commands work.

### ISSUE THREAD

**Issue by S0meDev99** [TinyCircuits/TinyCircuits-TinyShield-BLE-ASD2116#1]
Hi there, 
I am currently using two TinyZero with the Bluetooth TinyShield and am trying to establish a connection between both devices.
So far I am trying some of the functions with these parameters, in the example UART.ino :
1. ret = aci_gap_start_general_discovery_proc(0x4000, 0x4000,0x00,0x00);
2. ret = aci_gap_create_connection(0x4000, 0x4000, PUBLIC_ADDR, GAP_Peripheral_address, PUBLIC_ADDR, 40, 40, 0, 60, 2000 , 2000);
3. ret = aci_gap_create_connection(0x4000, 0x4000, PUBLIC_ADDR, GAP_Peripheral_address, PUBLIC_ADDR, 40, 40, 0, 60, 2000 , 2000);

The BLEsetup() function is run, followed by only the aci_loop() in the main loop() function. The above mentioned function calls are put inside a separate function and called in the aci_loop().
I checked the status variable return value and it was FF. Am I supposed to run a specific function first before?

In main.ino file
```
void loop() {
  aci_loop(); 
}
```

aci_loop() in UART.ino
```
void aci_loop() {
  HCI_Process();
  //GAP_Central_Make_Connection();
  GAP_Central_General_Discovery_Procedure();
  GAP_Central_Make_Auto_Connection();
  ble_connection_state = connected;
  if (set_connectable) {
    setConnectable();
    set_connectable = 0;
  }
  if (HCI_Queue_Empty()) {
    //Enter_LP_Sleep_Mode();
  }
}
```

Functions declared in UART.ino
```
void GAP_Central_Make_Connection(void )
{
	tBleStatus ret;
	tBDAddr GAP_Peripheral_address = {0xaa, 0x00, 0x00, 0xE1, 0x80, 0x02};
	ret = aci_gap_create_connection(0x4000, 0x4000, PUBLIC_ADDR, GAP_Peripheral_address, PUBLIC_ADDR, 40, 40, 0, 60, 2000 , 2000);
	if (ret != BLE_STATUS_SUCCESS) PRINTF("Failure.\n")
}

void GAP_Central_General_Discovery_Procedure(void)
{
	tBleStatus ret;
	ret = aci_gap_start_general_discovery_proc(0x4000, 0x4000,0x00,0x00);
	if (ret != BLE_STATUS_SUCCESS) PRINTF("Failure.\n")
}

void GAP_Central_Make_Auto_Connection(void) {
	tBleStatus ret;

 uint8_t addr_array[] = {PUBLIC_ADDR,0xaa, 0x00, 0x00, 0xE1, 0x80, 0x02};
	ret = aci_gap_start_auto_conn_establish_proc_IDB05A1(0x4000,0x4000,PUBLIC_ADDR,40,40,0,60,2000,2000,1,addr_array);
  if (ret != BLE_STATUS_SUCCESS) PRINTF("Failure.\n")
}
```

**Comment by TinyCircuits** [comment]
Hello! We do have an example for two ST Bluetooth and TinyZero stacks communicating with each other. We do not have it posted on Github, but we shared it on our forum in this thread: http://forum.tinycircuits.com/index.php?topic=2024.msg4659#msg4659
I believe those examples will be very helpful to you.

You will need to create an account and login in order to be able to access the example programs attached to messages.

**Comment by S0meDev99** [comment]
Ok, I see. Thank you very much.
